window.AURELIA = {
  clinic: {
    name: "Aurelia Dental",
    phone: "+7 (495) 000-00-00",
    phoneHref: "tel:+74950000000",
    email: "hello@aurelia-dental.ru",
    address: "Большая Никитская, 21, стр. 2, Москва",
    hours: "Пн–Сб 09:00–21:00"
  },
  doctors: {
    volkov: {
      id: "volkov",
      name: "Александр Волков",
      role: "Ведущий имплантолог",
      spec: "Имплантация · Хирургия",
      years: "17 лет практики",
      image: "assets/images/doctor-volkov.jpg",
      education: "Первый МГМУ им. Сеченова. Продвинутая имплантология, University of Bern.",
      approach: "Каждый случай имплантации — это архитектура: кость, прикус и видимая улыбка должны работать как единая система. Скорость никогда не цель. Стабильность — да.",
      interests: "Протоколы немедленной нагрузки, цифровые хирургические шаблоны, полная реабилитация.",
      conferences: "EAO Congress, ITI World Symposium, Московский форум цифровой имплантологии.",
      certs: ["European Association of Dental Implantology", "ITI Fellow curriculum", "Цифровое хирургическое планирование", "Клиническая резиденция All-on-4"]
    },
    morozova: {
      id: "morozova",
      name: "Елена Морозова",
      role: "Врач эстетической стоматологии",
      spec: "Виниры · Дизайн улыбки",
      years: "14 лет практики",
      image: "assets/images/doctor-morozova.jpg",
      education: "МГМСУ. Эстетическая резидентура, Милан.",
      approach: "Естественная улыбка никогда не копируется из каталога. Я работаю со светом, текстурой и тем, как человек уже говорит и смеётся.",
      interests: "Минимально инвазивная керамика, планирование через mock-up, подбор оттенка.",
      conferences: "AACD meeting, StyleItaliano, International Aesthetic Dentistry Symposium.",
      certs: ["StyleItaliano honorary training", "Мастер-класс по керамическим винирам", "Цифровой дизайн улыбки", "Фотография в стоматологии"]
    },
    sokolov: {
      id: "sokolov",
      name: "Дмитрий Соколов",
      role: "Ортодонт",
      spec: "Элайнеры · Коррекция прикуса",
      years: "12 лет практики",
      image: "assets/images/doctor-sokolov.jpg",
      education: "ПСПбГМУ им. Павлова. Специализация по ортодонтии.",
      approach: "Выравнивание — не косметический shortcut. Сначала корректируем функцию, затем линию улыбки.",
      interests: "Ортодонтия для взрослых, прозрачные элайнеры, междисциплинарные случаи с протезированием.",
      conferences: "Invisalign Summit, European Orthodontic Society, Russian Aligner Forum.",
      certs: ["Специалист по элайнерам", "Клинический курс Damon system", "Ортодонтия для взрослых", "Протокол скрининга ВНЧС"]
    },
    petrova: {
      id: "petrova",
      name: "Анна Петрова",
      role: "Эндодонт",
      spec: "Терапия · Лечение каналов",
      years: "11 лет практики",
      image: "assets/images/doctor-petrova.jpg",
      education: "РУДН. Микроскопная эндодонтия, University of Zurich.",
      approach: "Тихая, точная работа под увеличением. Если зуб можно сохранить предсказуемым протоколом — мы его сохраняем.",
      interests: "Микроскопная эндодонтия, консервативные реставрации, безболезненная диагностика.",
      conferences: "European Society of Endodontology, Microscope Dentistry Days.",
      certs: ["Микроскопная эндодонтия", "NiTi инструментарий", "Vital pulp therapy", "Интерпретация КЛКТ"]
    },
    orlov: {
      id: "orlov",
      name: "Михаил Орлов",
      role: "Ортопед",
      spec: "Коронки · Реставрационная стоматология",
      years: "15 лет практики",
      image: "assets/images/doctor-orlov.jpg",
      education: "Первый МГМУ. Специализация по ортопедической стоматологии.",
      approach: "Реставрации должны исчезать во рту. Я одержим контактами, оттенком и тем, как пациент будет жить с работой через десять лет.",
      interests: "Полностью керамические реставрации, случаи стираемости, имплантат-опора.",
      conferences: "EPA congress, Digital Dentistry Show, Ceramic Masters.",
      certs: ["Протокол полной керамики", "Окклюзия в реставрационной стоматологии", "CAD/CAM протезирование", "Имплантат-опора"]
    },
    ivanova: {
      id: "ivanova",
      name: "София Иванова",
      role: "Пародонтолог",
      spec: "Гигиена · Пародонтология",
      years: "9 лет практики",
      image: "assets/images/doctor-ivanova.jpg",
      education: "СЗГМУ. Специализация по пародонтологии.",
      approach: "Долговечность начинается с дёсен. Любой эстетический или имплантационный план силён ровно настолько, насколько здорова окружающая ткань.",
      interests: "Поддерживающая пародонтальная терапия, уход за периимплантатными тканями, профилактические протоколы.",
      conferences: "EuroPerio, Сессии Российского пародонтологического общества.",
      certs: ["Пародонтальная терапия", "Airflow prophylactic protocol", "Менеджмент периимплантита", "Работа с мягкими тканями"]
    }
  },
  prices: [
    { cat: "diagnostics", name: "Первичная консультация", price: "₽2 500", note: "45 минут" },
    { cat: "diagnostics", name: "Повторная консультация", price: "₽1 800", note: "30 минут" },
    { cat: "diagnostics", name: "ОПТГ", price: "₽2 200", note: "" },
    { cat: "diagnostics", name: "КЛКТ, одна челюсть", price: "₽6 500", note: "" },
    { cat: "diagnostics", name: "КЛКТ, обе челюсти", price: "₽9 800", note: "" },
    { cat: "diagnostics", name: "Внутриротовое сканирование", price: "₽4 500", note: "" },
    { cat: "hygiene", name: "Профессиональная гигиена", price: "от ₽5 500", note: "Airflow + scaling" },
    { cat: "hygiene", name: "Поддерживающий пародонтальный визит", price: "от ₽7 200", note: "" },
    { cat: "hygiene", name: "Фторирование / реминерализация", price: "₽2 800", note: "" },
    { cat: "therapy", name: "Анестезия", price: "₽900", note: "" },
    { cat: "therapy", name: "Композитная реставрация, 1 поверхность", price: "от ₽8 500", note: "" },
    { cat: "therapy", name: "Композитная реставрация, обширная", price: "от ₽14 000", note: "" },
    { cat: "therapy", name: "Лечение каналов, резец", price: "от ₽18 000", note: "Микроскоп" },
    { cat: "therapy", name: "Лечение каналов, мolar", price: "от ₽32 000", note: "Микроскоп" },
    { cat: "surgery", name: "Простое удаление", price: "от ₽6 500", note: "" },
    { cat: "surgery", name: "Хирургическое удаление", price: "от ₽12 000", note: "" },
    { cat: "surgery", name: "Удаление зуба мудрости", price: "от ₽16 000", note: "" },
    { cat: "surgery", name: "Пластика мягких тканей", price: "от ₽28 000", note: "" },
    { cat: "implants", name: "Установка импланта", price: "от ₽85 000", note: "Только имплант" },
    { cat: "implants", name: "Навигационная имплантация", price: "от ₽98 000", note: "" },
    { cat: "implants", name: "All-on-4, на челюсть", price: "от ₽390 000", note: "План после КЛКТ" },
    { cat: "implants", name: "Костная пластика", price: "от ₽35 000", note: "" },
    { cat: "implants", name: "Коронка на имплант", price: "от ₽48 000", note: "Цирконий" },
    { cat: "prosthetics", name: "Керамическая коронка", price: "от ₽32 000", note: "E.max / цирконий" },
    { cat: "prosthetics", name: "Мост, за единицу", price: "от ₽32 000", note: "" },
    { cat: "prosthetics", name: "Вкладка / накладка", price: "от ₽28 000", note: "" },
    { cat: "orthodontics", name: "Ортодонтическая консультация", price: "₽3 500", note: "" },
    { cat: "orthodontics", name: "Элайнеры, обе челюсти", price: "от ₽120 000", note: "" },
    { cat: "orthodontics", name: "Брекеты металлические", price: "от ₽95 000", note: "План на челюсть" },
    { cat: "orthodontics", name: "Брекеты керамические", price: "от ₽130 000", note: "" },
    { cat: "orthodontics", name: "Ретенция, на челюсть", price: "от ₽12 000", note: "" },
    { cat: "aesthetics", name: "Профессиональное отбеливание", price: "от ₽18 000", note: "В клинике" },
    { cat: "aesthetics", name: "Домашний набор для отбеливания", price: "от ₽14 000", note: "" },
    { cat: "aesthetics", name: "Керамический винир, за единицу", price: "от ₽35 000", note: "" },
    { cat: "aesthetics", name: "Mock-up дизайна улыбки", price: "от ₽18 000", note: "" },
    { cat: "aesthetics", name: "Композитная реставрация, за зуб", price: "от ₽12 000", note: "" }
  ],
  articles: {
    veneers: {
      slug: "veneers",
      title: "Как выбрать виниры, не потеряв свою улыбку",
      category: "Эстетика",
      date: "12 марта 2026",
      time: "7 мин чтения",
      author: "Елена Морозова",
      image: "assets/images/journal-1.jpg"
    },
    implants: {
      slug: "implants",
      title: "Чего ожидать от дental имплантации",
      category: "Имплантация",
      date: "28 февраля 2026",
      time: "8 мин чтения",
      author: "Александр Волков",
      image: "assets/images/journal-2.jpg"
    },
    whitening: {
      slug: "whitening",
      title: "Профессиональное отбеливание без мифов",
      category: "Эстетика",
      date: "4 февраля 2026",
      time: "5 мин чтения",
      author: "София Иванова",
      image: "assets/images/journal-3.jpg"
    },
    aligners: {
      slug: "aligners",
      title: "Как элайнеры реально двигают зубы",
      category: "Ортодонтия",
      date: "19 января 2026",
      time: "6 мин чтения",
      author: "Дмитрий Соколов",
      image: "assets/images/journal-4.jpg"
    },
    hygiene: {
      slug: "hygiene",
      title: "Гигиена, которая работает в реальной жизни",
      category: "Профилактика",
      date: "9 января 2026",
      time: "5 мин чтения",
      author: "София Иванова",
      image: "assets/images/journal-5.jpg"
    },
    consult: {
      slug: "consult",
      title: "Как подготовиться к первой консультации",
      category: "Визит",
      date: "18 декабря 2025",
      time: "4 мин чтения",
      author: "Координаторы Aurelia",
      image: "assets/images/journal-6.jpg"
    }
  }
};
